### ISSUE TITLE
タスク管理用のissueテンプレート を作成して欲しい

### ISSUE THREAD

**Issue by Geson-anko** [matsuo-group24-PinkTrombone/SpeechGeneration#2]
## 概要
タスクを書き込む用ののテンプレートが欲しいです。
そしてそのissueの下に小タスクを書き込んでいくスタイルを思い付いています。

## 背景と目的
タスクをissueにどんどん書いていく方針のため、その書き方が整理されていて欲しいです。

## 提案内容

--- issueのテンプレート ---
```
# タスクのタイトル
*ここにタスクの内容を記述します*

### 達成条件  
- [ ] aaaa
- [ ] bbbb

```

## タスク
- [ ] タスク投稿用のissueテンプレートを作成する

**Comment by takeshun256** [comment]
達成条件を複数連ねることができて良いと思いました！
タスクの優先度や締め切りは、Projects上でラベルとして設定できるので、これのテンプレートでPRを出したいと思います。
