### ISSUE TITLE
pre-commit実行時にprior_encoder関連ファイルでエラーが出る

### ISSUE THREAD

**Issue by seichi042I** [matsuo-group24-PinkTrombone/SpeechGeneration#49]
## 概要
pre-commitした際にprior_encoder関連ファイルでエラーが出る

## 発生環境
mianブランチ

## 再現手順
mainブランチ環境でターミナルで
`make format`
を実行する

## 修正しないとどう困るか
モジュールを追加する際のpre-commitで毎回追加機能と関係ないファイルの変更が発生する

## 原因
prior_encoderをコミットするときにpre-commitしていなかったのかもしれない

## 修正案
src/models/components/prior_encoder.py:15: dimention ==> dimension
src/models/components/prior_encoder.py:16: dimention ==> dimension
src/models/components/prior_encoder.py:17: standart ==> standard
src/models/components/prior_encoder.py:49: dimention ==> dimension
@cehl-kurage

**Comment by cehl-kurage** [comment]
タイポですね...
すみません！！！修正しておきます！！
