### ISSUE TITLE
Imagination Horizonを視覚的にうまく行っているか確認する機能を実装する。

### ISSUE THREAD

**Issue by Geson-anko** [matsuo-group24-PinkTrombone/SpeechGeneration#94]
## 概要
World Modelが世界をしっかりと近似できているかを視覚的に確認する機能を実装します。
## 背景と目的
2023/02/13日現在、実験は期待通りに動作していませんが、その原因の一つに世界モデルの予測が失敗している可能性が挙げられます。  それを視覚的に判断する機能がないため完全に失敗しているのか、精度か足りないだけなのか、わかりません。  
従って、それらを定性的に見る機能を実装する必要があります。  

## 提案内容
1. `evaluation_step`で`target_spectrogram`, `generated_spectrogram`, `predicted_generated_spectrogram`の3つを集める。
2. 集めた3つを`imshow`したMatplotlibを`Figure`クラスを作成する。  
3. tensorboardの`add_figure`で図形を記録する。

Note: `done`までの1エピソード分で記録する。

### 描画のイメージ
<img width="504" alt="image" src="https://user-images.githubusercontent.com/59220704/218388050-702c9920-6570-4087-aa46-a23c8d00d64a.png">

## タスク

- [ ] 上記の処理を実装した
- [ ] 期待通り動作していることが確かめられた。

## 参考
第７回演習の最後. display_videoのセルを参考に作成しました。

**Comment by cehl-kurage** [comment]
@Geson-anko 
### 質問
- target音声や`env`によるgenerate音声のメル化にはどういうパラメータを用いるべきでしょうか?

`obs_auto_encoder` が訓練されているメル尺度と target, generated のメル尺度がそろっていることを保証するにはどうすべきかを悩んでいます。
